services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:80"
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./gateway/.env.docker
    networks:
      - app-network

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./user/.env.docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
